### ISSUE TITLE
Admin Tool Configuration

### ISSUE THREAD

**Issue by cflottorp** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#102]
Admin Tool needs to be configured to run at system boot possibly via an init script

**Comment by coderReview** [comment]
The 0100_fit already set up Nodejs to always start during boot after apache has been started.

**Comment by cflottorp** [comment]
Confirmed and completed issue.

**Comment by rsial2** [comment]
Thanks @cflottorp, I'll close this issue.
