### ISSUE TITLE
Variable Repetition in Script

### ISSUE THREAD

**Issue by cflottorp** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#104]
In the FIT script itself, for ease of maintainability, avoid the repetition of the variables in the script. Desired completion date of 3/21/16

**Comment by rsial2** [comment]
In the FIT script itself, for ease of maintainability, avoid the repetition of the variables in the script. Desired completion date of 3/21/16

**Comment by briandmartin** [comment]
The latest delivery of FIT addresses this issue and concur with closing this issue.
