### ISSUE TITLE
Postgres vs Debian Commands

### ISSUE THREAD

**Issue by cflottorp** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#105]
In the FIT script, use Debian commands instead of the Postgres general functions presently in the script.  Examples to use are pg_dropcluster and pg_createcluster.  Desired completion date of 3/21/16

**Comment by briandmartin** [comment]
@rsial2 The latest delivery of FIT addresses this issue and concur with closing this issue.
