### ISSUE TITLE
Echoing of Passwords

### ISSUE THREAD

**Issue by cflottorp** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#106]
Possible unnecessary echoing of the passwords used within the FIT script.  Delete unnecessary echoing of passwords.  Desired completion date: 3/21/16

**Comment by coderReview** [comment]
Since the password is randomly created how do you suggest to output the generated passwords?

**Comment by rsial2** [comment]
No we do not have a better suggestion at this time.  Long term, the need to output the FIT Postgres DB admin account password should go away once the web service is implemented for the FIT iPad App and Postgres to interact with.  If it's decided that the web service is more long term than we should be OK buying off the risk of having the the password echo'd to the terminal in the near term. This would be knowing that the web service is ideally where we want to end up.

**Comment by briandmartin** [comment]
The latest delivery of FIT addresses this issue and concur with closing this issue.
