### ISSUE TITLE
Architecture Update

### ISSUE THREAD

**Issue by cflottorp** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#108]
Modify the architecture of the communication/access between the FIT iPad app to the Postgres to function with an intermediary webserver instead of directly accessing the Postgres. Desired completion date: June 2016

**Comment by coderReview** [comment]
To understand the solution:
1- Develop a webservice with an API to communicate with the Postgres database.
2- Modify the iPad application to work with the webservice instead of the Postgres database.

**Comment by rsial2** [comment]
Yes, concur that is the change we're requesting.

**Comment by rsial2** [comment]
Replacing this ticket with a new ticket based on information from the task order.
