### ISSUE TITLE
Password Change

### ISSUE THREAD

**Issue by cflottorp** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#109]
Future enhancement to reveal the password at initial access/connection of the FIT iPad app to the server.

**Comment by rsial2** [comment]
Future enhancement to reveal the password at initial access/connection of the FIT iPad app to the server.

**Comment by coderReview** [comment]
@cflottorp could you give more details on what exaclty you want to achieve? How is this related to the architectural change.

**Comment by MargaretAKlee** [comment]
**reveal the password at initial access/connection of the FIT iPad app to the server**. This is a change to the iPad app unrelated to any of the other changes submitted. The crew member has to enter the FIT machine password on the iPad. The suggestion is to allow the user to reveal the password for the server as it is being entered on the iPad app so the user can verify the correct password is entered. The reveal would be available the first time the password is entered only. Does that make sense?

**Comment by coderReview** [comment]
Right now the password is set in the iPad settings application. I can set it to empty the first time the application is open and make the user type the username/password (with a checkbox to reveal the password). After that you can change it in the iPad settings. Is this ok?

**Comment by MargaretAKlee** [comment]
Yes

Thanks,

Margaret Klee
margaret.a.klee@nasa.gov<mailto:margaret.a.klee@nasa.gov>
O: 281-483-3609; Personal cell: 713-542-1797

Lockheed Martin Corporation
Information Systems and Global Solutions - Civil
Human Health and Performance Contract

**Comment by rsial2** [comment]
Wait, I'm sorry @coderReview & @MargaretAKlee, but I'm not sure if that is okay. We should not be forcing the user to do anything. It needs to work like this:

1. User installs the ISS FIT app
2. User goes to the Apple Settings app.
3. User scrolls to the entry for ISS FIT within with Settings app.
4. The Password value for the "Server" field is masked, meaning it is not visible.
5. It should be visible by tapping an icon to reveal the password.

Please don't force a user to enter a password after the install, the default password should work fine.

Sound good?

CC @szwart

**Comment by MargaretAKlee** [comment]
@coderReview<https://github.com/coderReview>, @rsial2, and @szwart

We are talking about the iPad to server machine account for ISS FIT. When FIT is installed on ISS, the default password will not be valid. The password is maintained by the flight operations console folks so the crew member has to enter the password the on the iPad.  The username should be pl_fit or pl-fit (Cheryl do you know which is correct?)

We learned this the hard way with a different app.

**Comment by rsial2** [comment]
Ok, in that case I think @coderReview's proposal works.

Does that sound good to you @szwart

**Comment by rsial2** [comment]
Replacing this ticket with a new ticket based on information from the task order.
