### ISSUE TITLE
LS1 Server Script - Account Use

### ISSUE THREAD

**Issue by cflottorp** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#115]
In the LS1 Server Script (0100_fit), update the script for the Admin Tool to be executing under the FIT generated account, pl_fit, instead of the root account.

**Comment by rsial2** [comment]
@cflottorp this change has been implemented but not committed to Github. The modified files have been sent to you via email.

**Comment by cflottorp** [comment]
Nodejs is failing to start when the Server Script, 0100_fit is run with the changed privileges for the Admin Tool.  The log file and error messages will be e-mailed to you.

**Comment by rsial2** [comment]
Thanks @cflottorp.

@coderReview please look into this.

**Comment by rsial2** [comment]
Spoke with NASA. They figured the issue out. I'm closing this ticket.
