### ISSUE TITLE
Automatically Generate ISS FIT Reports

### ISSUE THREAD

**Issue by MargaretAKlee** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#116]
We need to be able to schedule the generation of ISS FIT reports so the reports can generated on a specified frequency. Path information, report type and report schedule shall be read from a configuration file co-located with the function.

**Comment by MargaretAKlee** [comment]
Make a Chron function that runs as pl_fit user. Acceptable scripting languages are Pearl, php, and Python

**Comment by rsial2** [comment]
@MargaretAKlee, can you please confirm that your comment above is in regards to the primary ask in the description of this ticket - or are they separate?

**Comment by coderReview** [comment]
@MargaretAKlee The report can be generated for a single user, many users or all users. It can be for the whole time or you can specify the begin and end dates.

So the configuration file would have 3 settings path, users and schedule :

path='path_to_output/

users='Name Name' -- a single user
users='Name Name;Name Name' -- many users
users='*' -- all

schedule='monthly'  -- can be monthly or weekly (endDate will be current date and startDate will be endDate -1 month for monthly or -1 week for weekly)

Is this ok?

**Comment by MargaretAKlee** [comment]
Yes – My comment is a clarification of the original task rather than a new one.

Thanks,

Margaret Klee
margaret.a.klee@nasa.gov<mailto:margaret.a.klee@nasa.gov>
O: 281-483-3609; Personal cell: 713-542-1797

Lockheed Martin Corporation
Information Systems and Global Solutions - Civil
Human Health and Performance Contract

**Comment by rsial2** [comment]
@MargaretAKlee please see the new questions above from @coderReview

**Comment by rsial2** [comment]
Replacing this ticket with a new ticket based on information from the task order.
