### ISSUE TITLE
Automated database update

### ISSUE THREAD

**Issue by MargaretAKlee** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#117]
One of the console operations experts suggested there should be an automated way to update the ISS FIT database by checking for the existence of a new food or crew file and importing the database if the file exists. The location of the food and crew files needs to be read from a configuration file. If there are other function performed with the Admin Tool we need to look at automation for those functions as well.

**Comment by rsial2** [comment]
I'm sorry @MargaretAKlee, I don't understand this change at all. Can you please clarify? I also don't see why we would work around the admin tool, which was created to manage the database of foods.

CC @szwart & @nasarader

**Comment by rsial2** [comment]
Replacing this ticket with a new ticket based on information from the task order.
