### ISSUE TITLE
Barcode reader

### ISSUE THREAD

**Issue by szwart** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#137]
We are having trouble scanning commercially available items.  One example is a Clif Bar.  Attached is an example of a Clif Bar barcode that we were not able to successfully scan (it indicated that the item was not found).  
![clif bar](https://cloud.githubusercontent.com/assets/11872594/17229257/65f931ce-54dc-11e6-85c8-489ddeab0742.JPG)

**Comment by coderReview** [comment]
@szwart The app can detect the barcode, but does not found in database. What is the barcode value inserted in the database?

**Comment by rsial2** [comment]
@szwart & @nasarader would you be able to ask someone to check the database and see what value is being stored there?

**Comment by szwart** [comment]
We have actually tried the bar code a few different ways - one with the leading number 7 and one staring with 2 and one with only the first 4 digits (starting with 7) b/c we were under the impressing it's only reading the first 4 digits of all barcodes (is that correct?).  The app successfully scans the barcode, but it indicates that the food is not found in the database.

**Comment by szwart** [comment]
Oops - sorry, didn't mean to close this thread.

**Comment by rsial2** [comment]
Thanks Sara.

@coderReview please review.

**Comment by coderReview** [comment]
@szwart 
when the barcode is not found in the database a popup is shown with the barcode that the iPad has detected. I've tried using the barcode in the image and I had no problem getting the correct barcode. Is there any possibility you try again and check the barcode that is displayed in the popup?

**Comment by coderReview** [comment]
One thing to notice is that when a barcode is scanned it's compared to the device's local database. So you need to make sure that the food being scanned has been synchronized with the iPad device.

**Comment by szwart** [comment]
I think we must be having issues with the device's local database connecting/synchronizing with the database on the server.  We've also noticed that when we add a new food item to the data.csv file and upload it to the server using the Admin Tool (in a test environment), that item did not show up on our iPads for the food we were testing.  If we can delete the old data.csv file before loading a new one each time there is something that we need to change, I think it might fix this problem.  The iPads seem to get the entire food database when it's the first time it's loaded but they don't seem to be getting incremental changes after the first load.

**Comment by coderReview** [comment]
@szwart 
ok. I think this issue is treated in another ticket. Are the issue with the barcode with foods added after the initial load done by the iPad devices?
Anyway, I've updated the barcode library to its newest version that also supports iOS 10.

**Comment by szwart** [comment]
OK.  We already have a ticket to request that the old data.csv file be deleted before importing a new one.  The barcode issues have in fact been after the initial load.  
Just curious - is the barcode reader only recognizing the first 4 digits?  Or the entire barcode?

**Comment by coderReview** [comment]
It's recognizing all barcode, but when matching to the database it uses only the 4 starting digits (this was in the original requirement).

**Comment by szwart** [comment]
Got it - thanks!

**Comment by rsial2** [comment]
@szwart confirmed that this was fixed via email. Closing this issue.
