### ISSUE TITLE
Barcode scanning deletes items in database

### ISSUE THREAD

**Issue by szwart** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#139]
We had a crewmember call down from ISS to report the following issue.  When an item is scanned that is in the database is followed by another scan of an item that is not in the database, the first item is permanently deleted from the food database for that iPad.  The item cannot be found using search functions or barcode anymore.  

Here are the steps to recreate the issue:
1.  Barcode scan an item in the database.
2.  Click Scan another barcode.
3.  Scan something not in the database.
4.  A message “Not Found” comes up.  Click OK.
5.  Click Cancel in the bottom right.
6.  Search for the original item scanned using the search tool and it is no longer available.

We tested this out on a local server and found that other iPads connecting to that same server are not affected.  The deleted food items are not actually deleting from the food database as viewed through the Admin Tool.  They are only deleted locally on the iPad that was used to scan the barcodes.  The only way to get the items back seems to be to reload the app or change the server password so that the food/users are reloaded.  

Any thoughts/suggestions would be appreciated.  Thanks!

**Comment by szwart** [comment]
This looks like it's getting better... if I scan a barcode that is in the database then scan 2-3 more items in the database and then try to scan another one that is not in the database, it tells me that item is not in the database and I click ok.  Then I click OK. There are no options on the screen to do anything at that point.  The only way to get out of that screen is to click one of the tabs at the bottom (Profile, Help) and then go back to the Consumption tab. Once I get back to the Consumption tab, the other items I had scanned before the one that is not in the database are not listed.

**Comment by rsial2** [comment]
@coderReview please work on this.

**Comment by coderReview** [comment]
@szwart can you post a screenshot?

**Comment by coderReview** [comment]
@rsial2 I've made a push request to improve the barcode scanning. 
@szwart see if it's working better.

**Comment by rsial2** [comment]
@coderReview I don't see the updated code in the repo. But I'm assuming you built it locally and published the .ipa to Hockeyapp? If yes, can you confirm?

@szwart, if Paulo confirms that the latest app has been pushed to Hockeyapp, here's what you need to do:
1. Go to your iPad and click on the HockeyApp app icon.
2. It opens Safari
3. Click on the ISS FIT logo
4. Under Latest Versions, click on the most recently updated row (which is today).
5. Click on the "Install Build" button
6. It'll then install the latest version over the air.

**Comment by rsial2** [comment]
@szwart you should have received an email from Hockeyapp with a link to install the latest version of the app.

**Comment by szwart** [comment]
Yes, I have the new build and will take a look now…

Thanks!
Sara

**Comment by szwart** [comment]
Looks like this is fixed!
