### ISSUE TITLE
Admin Tool Updates [Delete functionality]

### ISSUE THREAD

**Issue by rsial2** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#141]
Add a function to the Admin Tool for Maintenance of the Postgres data for the ISS FIT SQL database to delete records from the database. Specifically:

1. Given the following conditions:
1.1 The user is flagged data for deletion (isDeleted property = YES)
1.2The data has been processed (added to the server/downloaded from iPad (i.e. synchronized))
1.3The data has been sent to the ground (report generated)

2. The media files be placed in an “archive file” on the pl_fit account folder on the ls1 server (//ssc/dfs/pl_fit/).

3. Delete should be located on it’s own tab and have a verification question (“Do you really want to delete this data?”).

4. Add capability to delete crewmembers through a file uplink (either a importing a new crew file would archive all crewmembers not listed in the new crew file or uplinking a different file). This will reduce ground controller time to delete crew members.

**Comment by rsial2** [comment]
Was this completed?

**Comment by coderReview** [comment]
@rsial2 still working on this.

**Comment by rsial2** [comment]
When will it be completed? Please note we're behind schedule on this.

**Comment by rsial2** [comment]
@coderReview what is the status of this item?

**Comment by coderReview** [comment]
@rsial2 sorry for the delayed feedback. I was so involved with the other issues that only now I realized that the requirements are very confusing to me.

Let me see if I get it.
1- A list of food records that match the condition 1, 2 and 3. The only issue is that no 2 is not possible. I can't determine if all iPads have synchronized the data.
2- Media files are already sent with reports. Is this needed? This means that the media should also be removed.
3- ok.
4- I can make the same logic as the food import with a checkmark. 

I will start with the development. Please confirm my understanding.

**Comment by rsial2** [comment]
@cflottorp, can you please help with these questions?

**Comment by cflottorp** [comment]
Let me see if I can explain the reasoning for the need to clean up the Postgres database.  We have limited data storage for us to use on the server for our use. Over time, we will need the ability to delete the data associated with a user (crew member) from the database stored on the server.  However, before the data is deleted, we will need to make sure that the reports for that user have been completed prior to the deletion of the data.  Else we will lose that data by accidently deleting anything that hasn't already been sent in a report. The best way that we thought to ensure that all the data has been reported from the user was to verify that the data has been sent from the iPad (data from iPad downloaded to the server), then from the data on the server has been sent in a report.  If there is another method to clean up the data that you know would work better, let us know.

**Comment by rsial2** [comment]
@coderReview please share your thoughts.

**Comment by coderReview** [comment]
First thing. Before deleting a user, the iPad must synchronize its data to the database. There is no automatic way of knowing if the iPad has synchronize all its data. Therefore the first step is to login using this user and then logout. If no connection error is shown the data will be uploaded to the database. After a OK from the ISS crew saying that this user was synchronized you can remove it.
I will create a service that will delete this user. It will do the following:
1- dump user data into a file. This file will hold user data, food consumption record, ad hoc food created by user, media records.
2- will create a report with all data for that user
3- remove the records from the database and mark user as deleted.

Using the files from step one you can load it into a local database and use it offline.
And report data from step 2 can be viewed in Excel.
This way there is no need to keep track of generated reports, because one with all data will be provided before deleting. 
Step 3 will be available only after the data from 1 and 2 has been downloaded.
Are you ok with this procedure?
@cflorttop @rsial2

**Comment by rsial2** [comment]
@cflottorp can you confirm? 

@szwart FYI.

**Comment by cflottorp** [comment]
The steps outlined for the script to delete the user is acceptable

**Comment by rsial2** [comment]
@coderReview was this implemented?

**Comment by rsial2** [comment]
@coderReview do you have an update on this item?

**Comment by coderReview** [comment]
@rsial2 I will have this implement by tomorrow.

**Comment by rsial2** [comment]
@coderReview how's this coming along?

**Comment by coderReview** [comment]
@rsial2 almost done. Just need to dump database table. Already generating report and deleting database entries.

**Comment by coderReview** [comment]
After implementing the delete tab I've found that step 1 is not really needed

> 1- dump user data into a file. This file will hold user data, food consumption record, ad hoc food created by user, media records.

All needed information  (Food Name, Food Data, Food Consumption, Image and Audio) can be retrieved from report

**Code is in github and deployed in VM**

Will update DG and instruction tab after the automated script issue.

cc @cflottorp and @rsial2

**Comment by rsial2** [comment]
Thanks @coderReview, we can't consider this issue completed until the deployment guide, instruction tab and user guide have been updated. Please confirm.

**Comment by coderReview** [comment]
@rsial2 ok. Will have it done by Friday.

**Comment by rsial2** [comment]
Thanks, confirming that the guides have been updated (I got the pull request).

**Comment by nithyaasworld** [comment]
@coderReview Currently even after flagging the user for delete (In User Data  tab of Admin Tool), I am able to login with that user (in iPad app) and add foods. 

I think its not good to allow the user to login after marking the user for deletion. Please confirm.

**Comment by coderReview** [comment]
Were you online (with internet connection)? I will check what is going on.
Thanks

**Comment by nithyaasworld** [comment]
yes I was online.

Now, I deleted that user using Delete tab. A file was downloaded. After that It showed me a proxy error and VM is not accessible now. Please check.

![image](https://cloud.githubusercontent.com/assets/5114190/22185026/68b7536a-e103-11e6-873a-7c9150a6f535.png)

![image](https://cloud.githubusercontent.com/assets/5114190/22185031/791d5114-e103-11e6-877b-c8ee004aab51.png)

**Comment by coderReview** [comment]
@nithyaasworld server is back up

**Comment by nithyaasworld** [comment]
2--> After deleting the user using the Delete tab of Admin Tool, the user is still shown in the iPad app. On clicking login button, it displays a incorrect message "User already logged in another device"

**Comment by nithyaasworld** [comment]
3--> 

> Add capability to delete crewmembers through a file uplink (either a importing a new crew file would archive all crewmembers not listed in the new crew file or uplinking a different file). This will reduce ground controller time to delete crew members.

@coderReview I think this is not implemented. Please confirm.

**Comment by nithyaasworld** [comment]
4--> After deleting the user from Delete tab, I saw this error today. However User reports are downloaded automatically upon deletion.

![image](https://cloud.githubusercontent.com/assets/5114190/22248403/75e20b90-e264-11e6-9c07-e3a046f1f474.png)


5-->It seems only food data are exported before deletion. I am not seeing any user data. 

![image](https://cloud.githubusercontent.com/assets/5114190/22248476/c45722a6-e264-11e6-8215-02a65c3e99b6.png)

6--> I am not sure if this is  valid scenario. I entered some foods for Jan 25 (for tomorrow). After deleting the user, I am seeing data only till current day (that is Jan 24). Jan 25 data is not present in the exported data.

Exported file: [summary (3).zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/726760/summary.3.zip)

![image](https://cloud.githubusercontent.com/assets/5114190/22248551/19fefd32-e265-11e6-9a65-6ed20844fdd9.png)

7--> Those two issues found with report also exists here. That is,
(i) Exported report Protein and Sodium column has same value. 
(ii)Exported data time is not matching with the actual data.

![image](https://cloud.githubusercontent.com/assets/5114190/22248658/ab993488-e265-11e6-8efa-47a2a1033f5b.png)

**Comment by coderReview** [comment]
3- yes. The user is marked as removed and you can find it in the delete tab. my opinion is that the total user removal has to be a manual step. One by one to avoid mistakes. @rsial2 please confirm
4- first report is downloaded and afterwards the user is deleted. Does this happen all the time for a given user?
5- please see my comments above. No user data is being exported as it easy to recover this data, specially if it was used a CSV to load users to application.
6, 7 @nythiaasworld please confirm that all data is in database. The report is a exact match from database, but you need to make sure that data has been synchronized from iPad to database.

**Comment by nithyaasworld** [comment]
**1,2  - Yet to fix
3 - Need confirmation from @rsial2** 
4- Yes. While the report started to download, user is deleted.
I did not see that error when I tried last time. I will update you if it occurs again
**5- Can you please explain how do I get the report of a deleted user-data? Thanks. (I am not able to find it)**
6 - This is discussed as part of #146 
7- I will check this once again. If this is an issue, I will report it as part of #146 

@coderReview Please look into the Bold ones above.

**Comment by rsial2** [comment]
3 - confirmed @coderReview & @nithyaasworld

**Comment by coderReview** [comment]
@nithyaasworld please test again and let me know what is still an issue (see all other related issues).

**Comment by nithyaasworld** [comment]
**1,2 - Yet to fix**
3 - No Fix needed. 
4- Yes. While the report started to download, user is deleted.
I did not see that error when I tried last time. I will update you if it occurs again
**5- Can you please explain how do I get the report of a deleted user-data? Thanks. (I am not able to find it)**
6 - This is discussed as part of #146
7- I will check this once again. If this is an issue, I will report it as part of #146 

@coderReview I retested again. Please look into the Bold ones above.

**Comment by coderReview** [comment]
> Can you please explain how do I get the report of a deleted user-data? Thanks. (I am not able to find it)
What do you mean?

**Comment by nithyaasworld** [comment]
> 5- please see my comments above. No user data is being exported as it easy to recover this data, specially if it was used a CSV to load users to application.

how do we recover user data? I thought the zip file that is obtained after removing the user would have all data (both food and user data).

**Comment by coderReview** [comment]
User data is just name and profile image. This is simple to recover. Also, when the report is genarated you have the name of the user in the containing folder. The most important information is food and food consumption information.

**Comment by nithyaasworld** [comment]
The server went down after I deleted an user from Delete tab. Please check.

![image](https://cloud.githubusercontent.com/assets/5114190/22516108/c22d5a38-e8ca-11e6-8d78-83877729be42.png)

**Comment by nithyaasworld** [comment]
It was UP.

I again performed the same action (deleting an user from Delete tab). It went down now.

**Comment by nithyaasworld** [comment]
> User data is just name and profile image. This is simple to recover. Also, when the report is genarated you have the name of the user in the containing folder. The most important information is food and food consumption.

I just want to make sure that we are not losing any data after deleting an user. Do we have copy of these data marked in the screenshot? Or it is not necessary?

![image](https://cloud.githubusercontent.com/assets/5114190/22516908/6307511e-e8cd-11e6-97c4-c9c21955868c.png)

**Comment by coderReview** [comment]
@rsial2 and @szwart do we need to save such information? Specially because they could change over time. Right now we have user name, food and food consumption information. Please confirm
Thanks

**Comment by szwart** [comment]
No - we will have a record of all of that when we load it into their user profile csv file.  User name, food, and food consumption data is what we need.

**Comment by coderReview** [comment]
@nithyaasworld I will check the server crash. Thanks

**Comment by coderReview** [comment]
@nithyaasworld crash was fixed. Thanks

**Comment by coderReview** [comment]
@nithyaasworld Just one thing though. Before deleting user in Delete tab, you must make sure to synchronize all iPad devices/simulators first.

**Comment by nithyaasworld** [comment]
Thanks Paulo. There is no crash now.

There is one thing. Once I delete the user from User tab and then try to login in iPad, it says "User was removed" and then the user_thumbnail is removed from iPad app. This is as expected.

But when I delete the user from Delete tab and then try to login in iPad, it says "User already logged in another device". This should be fixed.

**Comment by nithyaasworld** [comment]
I also have one question: The report generated while deleting a user is same as the one generated when using the Report tab. Correct?

(I am asking this, so I do not have to verify the reports twice in detail.)

**Comment by coderReview** [comment]
Yes. It's the same report. The add food details flag is always on.

**Comment by nithyaasworld** [comment]
@coderReview I uploaded an user via the Automated Script. I deleted the same user using User Tab. Then I deleted the same user from Delete Tab. At this point, I see the below error:

However Reports are generated.

![image](https://cloud.githubusercontent.com/assets/5114190/22616178/2a0e2902-eace-11e6-96e1-801be656b92d.png)

**Comment by coderReview** [comment]
@nithyaasworld you always get the report, even if the user don't get deleted. However I've fixed it.
Try again.

**Comment by nithyaasworld** [comment]
Delete Functionality is verified.

In Admin Tool, On Deleting a User from User Tab, it is moved to Delete Tab. At this point, User is not available in iPad too.
Then further Admin can delete the user from Delete Tab. On Deleting, A report with Username, Food Consumption list is downloaded automatically.

Note: Any issues found with Report will be reported separately.

**Comment by nithyaasworld** [comment]
Paulo~

I see issues that were fixed and verified previously:

1. Able to login in ipad after deleting user from Delete tab
2. Server crashed after Delete process got completed (proxy error shown for Admin Tool)

**Comment by nithyaasworld** [comment]
Delete Functionality is working when the iPad has correct time.

Anything related to syncing with db when device time is not correct, will be reported as part of 138
