### ISSUE TITLE
Automated Import of Files

### ISSUE THREAD

**Issue by rsial2** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#142]
Automate the import of files (food, crew and crew photos). Crew photo should automatically be linked to crew (require no action in Admin tool.)

**Comment by coderReview** [comment]
How exactly you want to automate? A script to load data into the system

**Comment by cflottorp** [comment]
Currently in the User Data data file, there is a column labeled "Profile Image".  Could that column of data upload the photo or link the photo to that user.  That would automate the crew photo.  Then a script to load the files (User Data and Data).  From what I understand, these files are always named "User Data" and "Data" for the user profile information and the food database.  The user data file is updated at least every 6 months, so they would like a script to automate the import of the files.

**Comment by coderReview** [comment]
@cflottorp 
Regarding photo, I've proposed to upload a zip file with all images listed in the User Data file.
About the script automation, where would this script run?

**Comment by cflottorp** [comment]
The Admin Tool would probably be the only way our ground personnel would be able to access it.

**Comment by coderReview** [comment]
@cflottorp, I didn't understand if I need to automate anything.

**Comment by cflottorp** [comment]
currently, the photo for each of the users needs to be individually imported into the profile by the ground users using the Admin Tool. Which is time consuming by the ground personnel when they only have a limited window of time to use.  By providing a zip file that will be picked up by the software process to incorporate the images into the profile will help with the photos. However, with the import of the data (User Data, Data[food]) files, currently only one can be imported at a time.  Putting both files and selecting the "import" only imports the first file.

**Comment by coderReview** [comment]
Do you want to allow multiple User CVS files to be imported?
When you select User and Food files they should both be imported not only one. I will check once again and fix it if necessary.

**Comment by cflottorp** [comment]
They were hoping to have the all the files automatically imported at once.  Can that be done with a script file that looks for a certain location and then imports the files.

**Comment by coderReview** [comment]
This can't be done using a browser. Browser don't have access to file in computer, only when you upload a file. I can add multiple files upload. How many do you need for User and Food?

**Comment by cflottorp** [comment]
Then if the process is for the uploading the file, if the location is always known it can automatically upload those files?

**Comment by rsial2** [comment]
@coderReview please confirm.

**Comment by coderReview** [comment]
@rsial2 completed. Added an input for zip with images for users. 

> Then if the process is for the uploading the file, if the location is always known it can automatically upload those files?

This can't be done using browser. A different script must be used, like python. This is not related to the Admin tool. 

Please confirm if that is the case.

**Comment by cflottorp** [comment]
OK, then another script will be needed to automatically upload the files.

**Comment by coderReview** [comment]
@cflottorp In which machine you plan to run these scripts? Windows, linux?

**Comment by cflottorp** [comment]
They prefer to have the scripts run in a Windows environment

**Comment by coderReview** [comment]
@cflottorp can you give more specifications? What language you want to use? Python? Which version? How do you plan to make it run automatically? Will this machine have access to the Web service?
@rsial2 this is not related to Admin Tool or iPad app. This is something we need to gather the requirements to outline a solution.

**Comment by rsial2** [comment]
Thanks Paulo.

Cheryl, looking forward to your feedback on the new questions above.

**Comment by cflottorp** [comment]
Most of the batch files that are run use Windows, however, I do not know if that will create issues between the server and script.

**Comment by rsial2** [comment]
does that answer all of your questions @coderReview?

**Comment by rsial2** [comment]
@coderReview do you have an update?

**Comment by coderReview** [comment]
@rsial2 I will prepare a executable file to upload files to Admin Tool. However I can't make it run periodically, since this is a configuration in the Windows machine. Does this work?

**Comment by rsial2** [comment]
@coderReview, we'll need NASA to confirm.

@cflottorp, can you confirm how we should handle this? See the proposal above from Paulo.

**Comment by coderReview** [comment]
@rsial2 I can make the folder where the files to be imported should be located configurable. Thanks

**Comment by cflottorp** [comment]
That should work.

**Comment by cflottorp** [comment]
Currently, the reports for Sara and Scott are run on a weekly basis which works out well.  The importing of the data files (user profiles, user photos and food data) are usually performed on a 6 month basis (but unknown as to the exact date) so if the files are placed in a folder where we can configure for each rotation that should work out well. Thanks,

**Comment by rsial2** [comment]
@cflottorp, thanks for the update.

@coderReview, please make the changes as mentioned above.

**Comment by rsial2** [comment]
@coderReview were you able to work on this?

**Comment by rsial2** [comment]
@coderReview please provide an update.

**Comment by coderReview** [comment]
@rsial2 done

**Comment by nithyaasworld** [comment]
@coderReview 

In the config.ini file, it seems like I should be able to configure only the filepath and not the folder path. Please confirm.

I thought I should be able to specify the **folder path** of Food data, User data and ProfileImage files, so all files in those folders will be uploaded on executing this script.

```
[Food]
filename=c:\\Temp\\Food.csv

[User]
filename=c:\\Temp\\User.csv

[UserImage]
filename=c:\\Temp\\UserImage.csv

[Executed]
folder=c:\\Temp\\Executed
```

**Comment by coderReview** [comment]
I think we don't loose any functionality by providing the file's name. Also, we need one file for user and one for user image. If we have multiple files we can have other issues.

**Comment by coderReview** [comment]
@cflottorp please confirm if this acceptable

**Comment by nithyaasworld** [comment]
@coderReview Also we need to have option to upload multiple user image files. Because in a User File, there will be lot of users. As per the issue-description, it seems we need to map the userimage file name in the Profile image column of User_Data file. So on uploading a user_Data, its corresponding profile image should  get automatically linked to the profile.

**Comment by nithyaasworld** [comment]
@coderReview Also I think the idea of automating is, one should be able to upload multiple files in one go. Not just configure one file at a time and execute the script.

your thoughts please?

**Comment by cflottorp** [comment]
Yes, you are correct.  Currently we have to upload each file for the images per user. Then the food data and the user data files.   The idea for the automation was for all the files to all be automated else we will be doing the same function as before by uploading each file. All the files were to be loaded at one time.

**Comment by nithyaasworld** [comment]
@cflottorp Just to double confirm, there will be one folder which will have One food_Data file and One User_data File and multiple crew-photo files.  On specifying the location of folder path, all the files in that folder should get uploaded and photos should get linked to corresponding profile. Correct?

**Comment by coderReview** [comment]
@nithyaasworld you can't upload image files. You upload a CSV with user data and a Zip file with the images. The image file is unzipped and the file's name is matched against the data inside the CSV file.
What I have done is automated this process but you can't upload multiple user CSV files and image.

**Comment by coderReview** [comment]
You can't have more than one pair of user file and user image in the folder. That is why I didn't use folder in config.

**Comment by nithyaasworld** [comment]
@coderReview Ok. Thank You. That sounds good. I will verify.

**Comment by nithyaasworld** [comment]
@coderReview 

1. When I did not have a folder name called "executed", it still showed me success message along with errors. In that case, can we just show the error message without the success message?

![image](https://cloud.githubusercontent.com/assets/5114190/22214991/bf45551c-e1bf-11e6-876d-db29347d0867.png)

2. After importing, it showed me success message and user file and food file are moved to executed folder. But those data are not actually uploaded. Can you please check this?

[testdata.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/724459/testdata.zip)

**Comment by nithyaasworld** [comment]
@coderReview while uploading the food data via the script, it will mark all the existing entry as deleted?

**Comment by nithyaasworld** [comment]
Issues 1, 2 still exist.

Tested with the below data: 
[testdatajan30.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/738117/testdatajan30.zip)

**Comment by coderReview** [comment]
Are you sure 1 is still an issue?

2- fixed.
3- No it won't. I've added a command line argument `-f`. Please check the updated README.md inside the **Automated Scripts** folder.

**Comment by nithyaasworld** [comment]
1--> Yes. This happened when I last tested (8 hours ago).

![image](https://cloud.githubusercontent.com/assets/5114190/22421753/c8c74b50-e70e-11e6-8cc9-58281e9cabc3.png)

2-->  I will verify now
3--> Inside the Readme.md file of Automated Scripts folder, I couldn't find anything new.

**Comment by nithyaasworld** [comment]
2--> On running the script now, nothing is happening, it is stuck.

After executing the 

>  python send-files.py -c config.ini

it was stuck for more than 4 minutes. So I had to manually quit it by ctrl+Z.

is there any change in the config.ini file or the script file? Repository is not updated. So I used the same script.

**Comment by coderReview** [comment]
@nithyaasworld please try again. @rsial2 has deployed the new code to repository.

**Comment by nithyaasworld** [comment]
Tried with the latest code.

It took long time (more than 5 mins) and then displayed the below error.

Tried with both "f" in command and without "f" too.

![image](https://cloud.githubusercontent.com/assets/5114190/22464298/2adda046-e7dc-11e6-8156-27b0d81a5e45.png)

**Comment by nithyaasworld** [comment]
I noticed today that the User that was in User data csv file got uploaded because of running the above script file yesterday.

But that User has no image in his profile though I had image file in the test data.

**Comment by coderReview** [comment]
@nithyaasworld I am managing to send the files without any issues. Can you send the data files  and the config.ini file you are using?

**Comment by nithyaasworld** [comment]
Ok. I tried one more time. It took me 4 minutes and then displayed the same error as in the screenshot above.

However, On a quick glance I can see that User data and food data are added and visible in Admin Tool as in the csv. But the User data has no image attached to it though I have specified one during the upload.

Here are the files that I used for testing yesterday: 
[testdata (1).zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/747437/testdata.1.zip)

**Comment by coderReview** [comment]
Please use this file.

[testdata paulo.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/747805/testdata.paulo.zip)

**Comment by nithyaasworld** [comment]
I still see same error with the above data too.

However the Food and User data got uploaded. User data got uploaded with no profile pic (username: Feb02 Test01)

**Comment by coderReview** [comment]
Can you save the CSV files with unix format (line ends).

**Comment by nithyaasworld** [comment]
@coderReview Paulo, Server went down after I performed the following step

I tried to ran the automated script with 50 users in User.CSV and some 15 food products in Food.CSV.

I used the command:  python send-files.py -c config.ini -f

test data used: 
[UserImage.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/752784/UserImage.zip)
[User.csv.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/752785/User.csv.zip)
[Food.csv.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/752787/Food.csv.zip)

**Comment by coderReview** [comment]
Fixed

**Comment by nithyaasworld** [comment]
Ok. There is NO Server crash now.

One last small change for this ticket. 

In the Config.ini file, can you please change the following line

From: 
filename=c:\\Temp\\UserImage.**csv**

To: 
filename=c:\\Temp\\UserImage.**zip**

[ Though it is configurable, It initially confused me to see image file format as .csv. ]

**Comment by nithyaasworld** [comment]
**Test Summary:** 

> Automate the import of files (food, crew and crew photos). Crew photo should automatically be linked to crew (require no action in Admin tool.)

Verified.

(Just a note that Profile pics are expected to be only in .jpg file format, else it will not get uploaded.)

> When you select User and Food files they should both be imported not only one. I will check once again and fix it if necessary.

Verified.

> Yes, you are correct.  Currently we have to upload each file for the images per user. Then the food data and the user data files.   The idea for the automation was for all the files to all be automated else we will be doing the same function as before by uploading each file. All the files were to be loaded at one time.

Just a note that, Import tab in Admin Tool can be used instead of Automation script if needed. Import tab now has option to load image files, user file, food file - all at once and it works well.

Thanks Paulo!

**Comment by coderReview** [comment]
> In the Config.ini file, can you please change the following line
>
> From:
filename=c:\Temp\UserImage.csv
>
> To:
filename=c:\Temp\UserImage.zip
>
>[ Though it is configurable, It initially confused me to see image file format as .csv. ]

Done. cc @nithyaasworld
