### ISSUE TITLE
iPad Database Settings

### ISSUE THREAD

**Issue by rsial2** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#143]
Change the iPad Database settings to allow the use of a designated name (“ls1”) or IP address.

**Comment by coderReview** [comment]
What does this mean exactly? Instead of using an ip address use a host name?

**Comment by cflottorp** [comment]
Correct.  Would having the option to have both be possible?

**Comment by coderReview** [comment]
You don't need to use the ip address. It can be either an ip address or a valid hostname (the iPad must point to a DNS server that knows about the hostname).

**Comment by cflottorp** [comment]
If it is a virtual host?

**Comment by coderReview** [comment]
What do you mean virtual host? Running on a virtual machine?

**Comment by cflottorp** [comment]
I’m going to get more information from the person who requested the addition.  It doesn’t work on our end using the host name and I’m trying to nail down the possible issue.

Our server’s virtual hosting for the Admin Tool is setup with a virtualhost proxypass through Apache2 to the Node.js server.

**Comment by coderReview** [comment]
@cflottorp the only way to use a name instead of the IP is that in the local network a DNS server is present to provide the IP address based on the host's name.

**Comment by rsial2** [comment]
Hi @cflottorp, just checking in on this.

**Comment by coderReview** [comment]
@rsial2 this can't be fixed. We need a dns server to allow hostname.

**Comment by rsial2** [comment]
hi @cflottorp would NASA want to set that up, or use a pre-existing one?

**Comment by cflottorp** [comment]
This may be something that NASA would have to do so I’m trying to confirm with the server owners.  I will need a couple of days to get their response.

**Comment by cflottorp** [comment]
no response from owners yet.

**Comment by rsial2** [comment]
@cflottorp have you heard anything about this yet?

**Comment by cflottorp** [comment]
This change for the use of the hostname will need to be implemented by NASA if needed due to the architecture of the LS1 server and iPad interface, and with the way the permissions/access is set up in the network.

**Comment by rsial2** [comment]
Thanks, I'll close this ticket.
