### ISSUE TITLE
Food Inventory Update

### ISSUE THREAD

**Issue by rsial2** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#145]
In the Food Inventory, change the order of the Supplements line so that it is one section higher (before favorite foods) and appears on the main Inventory screen without having to scroll down to see it.

**Comment by coderReview** [comment]
@rsial2 this is fixed. Will commit the code.

**Comment by coderReview** [comment]
@rsial2 Fixed. Code committed.

**Comment by nithyaasworld** [comment]
Vitamins/Supplements section is visible without having to scroll.

![image](https://cloud.githubusercontent.com/assets/5114190/22184156/38e01318-e0f2-11e6-8c08-c00a9e8273f3.png)
