### ISSUE TITLE
Admin Tool Reporting Update

### ISSUE THREAD

**Issue by rsial2** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#146]
Add a function to the Reports within the Admin Tool that will pull a report of calories, sodium, fluid, protein, carbs, fat in addition to the raw food data.

**Comment by rsial2** [comment]
Was this completed?

**Comment by coderReview** [comment]
@rsial2 this is fixed. Will commit the code.

**Comment by coderReview** [comment]
@rsial2 Fixed. The admin tool already in VM already has the new code. Will commit to github shortly.

**Comment by coderReview** [comment]
Committed

**Comment by nithyaasworld** [comment]
In the Report, Protein and Sodium has same data for all food items. Seems like protein has incorrect value.

@coderReview Please check

![image](https://cloud.githubusercontent.com/assets/5114190/22184244/db550d0a-e0f3-11e6-99db-7db72185369e.png)

**Comment by nithyaasworld** [comment]
Protein and Sodium has correct value now. 

Please check the following:

1. "Comments" are not exported in Report
2. Entries in future date are not exported

**Comment by coderReview** [comment]
1- the code is exporting comments. Can you point to a step by step that this hasn't  worked
2- Normally no report will have this entries. And it doesn't make sense because user didn't make use of that food. This type of entry could be a mistake or an anticipation. In both cases of the user gets deleted before that date this food consumptions records should not be taken into account.

**Comment by nithyaasworld** [comment]
1--> Login as user "DeleteUser Testing", Add a Food to consumption list and then add a comment. Logout and login again and see that the comment is still present.
Now in Admin Tool, Export the report for this user and observe that entry is present without the comment.

![image](https://cloud.githubusercontent.com/assets/5114190/22395174/e674fa58-e55b-11e6-899c-05e12223ba9b.png)

![image](https://cloud.githubusercontent.com/assets/5114190/22395183/13d485d6-e55c-11e6-844f-93401243eb26.png)

**Comment by nithyaasworld** [comment]
> 2- Normally no report will have this entries. And it doesn't make sense because user didn't make use of that food. This type of entry could be a mistake or an anticipation. In both cases of the user gets deleted before that date this food consumptions records should not be taken into account.

Good point. I agree.

**Comment by nithyaasworld** [comment]
Thanks Paulo.

The above issues are solved.

When I choose "All Users Food Data Report", it is fetching empty folders without any food reports.

![image](https://cloud.githubusercontent.com/assets/5114190/22405855/bfad4c54-e66e-11e6-8197-0db03350277e.png)

**Comment by nithyaasworld** [comment]
Issue still exists. is the Fix deployed to VM?

**Comment by coderReview** [comment]
Yes. Can you paste the results?

**Comment by coderReview** [comment]
All users in database that are not removed will appear in the report.

**Comment by nithyaasworld** [comment]
But the folders are empty.

This is the Report generated: 
[summary (19).zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/738916/summary.19.zip)

**Comment by coderReview** [comment]
Does these have any food record in app?

**Comment by coderReview** [comment]
Found the issue

**Comment by nithyaasworld** [comment]
Also there is a folder called "media" which does not seem to have valid info.

![image](https://cloud.githubusercontent.com/assets/5114190/22423866/cac2d54a-e719-11e6-8c4d-726ff05f2c14.png)

**Comment by coderReview** [comment]
Fixed.

**Comment by nithyaasworld** [comment]
Verified.

(All the previous issues in this ticket are also re-verified)
