### ISSUE TITLE
Architecture Document Update

### ISSUE THREAD

**Issue by rsial2** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#148]
Update the architecture document based on all changes made during round 12.

**Comment by rsial2** [comment]
When will you be able to submit this for review?

**Comment by coderReview** [comment]
@rsial2 I will double check. But the last changes didn't touch the architecture.

**Comment by rsial2** [comment]
Thanks, just need confirmation.

**Comment by rsial2** [comment]
@coderReview have you been able to confirm?

**Comment by coderReview** [comment]
@rsial2 Fixed. Code committed.
