### ISSUE TITLE
Deployment Guide Update

### ISSUE THREAD

**Issue by rsial2** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#149]
Update the deployment guide based on all changes made during round 12.

**Comment by rsial2** [comment]
When will you be able to submit this for review?

**Comment by coderReview** [comment]
@rsial2 I think I will need some images in the help and user guide. will fix this today.

**Comment by rsial2** [comment]
Thanks, we're behind schedule on this one, so please confirm when done.

**Comment by rsial2** [comment]
@coderReview what is the ETA on this?

**Comment by coderReview** [comment]
@rsial2 Fixed. Code committed.
