### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by szwart** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#151]
Paulo - FYI, Holly and I are both having issues logging in.  For any user we pick, we get a message that pops up stating "User already logged in another device".  Are all of the users currently logged in on your devices?

**Comment by rsial2** [comment]
@coderReview see above.

**Comment by szwart** [comment]
Sorry for the distraction - I realized I wasn't connected to our wifi.  Once I was connected, I'm able to log in using any of the users.  However, I'm still getting a message that comes up saying "Error.  We are unable to sync this iPad with the central food repository.  Don't worry! You can still use...".  So it appears to let me connect in order to log in, but not to the food repository.  Could this be a NASA firewall issue like we had in the past?

**Comment by rsial2** [comment]
@szwart can you try on a non-NASA network? If it works then it's the NASA firewall.

**Comment by szwart** [comment]
I tried connecting using my phone hotspot and it’s still giving me that message.

**Comment by coderReview** [comment]
@szwart I will check the server is up and running.

**Comment by coderReview** [comment]
@szwart Server is running fine. Will check the iPad app.

**Comment by szwart** [comment]
Holly says hers is not giving her that error message.  So it appears to only be mine.  Maybe I should try to reload the app?

**Comment by coderReview** [comment]
Can you paste the app config?
Em qui, 12 de jan de 2017 às 11:40, szwart <notifications@github.com>
escreveu:

**Comment by rsial2** [comment]
@coderReview can you confirm how to do that? Do you mean from the Settings app?

**Comment by coderReview** [comment]
Yes.

**Comment by rsial2** [comment]
Thanks Paulo.

@szwart can you upload the screenshot please.

**Comment by szwart** [comment]
![ipad screenshot](https://cloud.githubusercontent.com/assets/11872594/21909755/e09a5512-d8de-11e6-81a4-c938cc66b2ff.JPG)
Let me know if this is not what you were looking for...

**Comment by coderReview** [comment]
@szwart that seems correct. I've provided a new version of the iPad app. Can you try a fresh install?

**Comment by szwart** [comment]
It works now!  I don't get that error anymore.  Thanks!!
