### ISSUE TITLE
App crashes when logging in for the very first time with a newly created user

### ISSUE THREAD

**Issue by nithyaasworld** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#157]
iPad 4 iOS 10.2

1. Open the app and create a new user
2. Try to login with the newly created user and observe

Actual:

App crashes when logging in with the newly created user for the first time.

Expected:

No crash.

**Comment by nithyaasworld** [comment]
I tried again with the latest code. It still crashes. Can you please check?

**Comment by nithyaasworld** [comment]
The above issue is fixed. But I see another issue now.

After logging in, I added a food to consumption list, then I immediately logged out. Then after syncing is done (after loading symbol stopped spinning), I tried to login. It is showing me the same login screen. When I again try to login, it crashes.

Reproducible Rate: 3/3

Video: 
[2.mp4.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/731599/2.mp4.zip)

Crash log:
FoodIntakeTracker-2017-01-26-111801.crash

**Comment by coderReview** [comment]
@nithyaasworld are you changing the Identifier to com.nithya.FoodIntakeTracker? 
I will upload a new version in Hockeyapp. This way I can get the crash logs. Ok?

**Comment by nithyaasworld** [comment]
Yes. 
Ok. Thanks.

**Comment by coderReview** [comment]
@nithyaasworld new version was uploaded to HockeyApp

**Comment by nithyaasworld** [comment]
It crashed again now for the same scenario above https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/issues/157#issuecomment-275311234.  I have clicked the "Send Report" button. Hope you have received the crash log. Please check.

**Comment by coderReview** [comment]
@nithyaasworld can you check if this is reproducible in simulator or is a device only issue? Thanks

**Comment by nithyaasworld** [comment]
There is no crash in the simulator (Tested with the latest code available in the repository).

However it did not login when I clicked on Login after logout. It showed the same login screen. Then when I tried to login again, it logged me in. But this happened only one time. All other time, there was no problem in simulator.

**Comment by nithyaasworld** [comment]
No crash now. But I would like to recheck this once #164 is fixed.

**Comment by nithyaasworld** [comment]
No Crashes now.
