### ISSUE TITLE
iPad App: Quantity and Time are not getting saved

### ISSUE THREAD

**Issue by nithyaasworld** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#158]
iPad 4 iOS 10.2

1. Login as any user in the ipad app
2. Add the food item "Altoids Mints"
3. Change its quantity to any other values (say 2 pkg)
4. Logout and login again and observe 

Actual:

1. The package value selected was not preserved
2. when I set the drinking water package value to 2.5, it preserves only the whole numbers not the decimals. So it is saved as 2 instead of 2.5
3. After modifying the quantity and logging out and trying to log in again, sometimes crashes the app, sometimes it displays the same login screen 

Expected:

Selected value must be preserved. 

No issue is expected while logging in again.

![image](https://cloud.githubusercontent.com/assets/5114190/22219264/2066bdd0-e1d0-11e6-80ea-7e5606c06a52.png)

**Comment by nithyaasworld** [comment]
Similarly, modified Time value is also not getting preserved after logging out.

**Comment by nithyaasworld** [comment]
Pass.

Modified Quantity and Time values are preserved.

**Comment by nithyaasworld** [comment]
Now the Time and Quantity I entered are **sometimes** not getting saved. It is set back to its previous value.

Reproducible Rate for Time: 3/5
Reproducible Rate for Quantity: 1/5

Video: Please watch from 35th second -> 
[1.mp4.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/745444/1.mp4.zip)

**Comment by coderReview** [comment]
@nithyaasworld can you send me the logs?

**Comment by nithyaasworld** [comment]
I am not able to reproduce today. Tried for about 5 times. All the times it worked correctly.

Closing this.
