### ISSUE TITLE
Not able to sync with Central Repository though I have active internet

### ISSUE THREAD

**Issue by nithyaasworld** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#164]
I was retesting #157. For that, I needed to Login and Logout several times after adding/removing food to consumption list. At one time, after logging out, it was not syncing to Central Repository. 

I closed and re-opened the app, but no luck. I see the below error. 

Device Log:
[log.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/745048/log.zip)

![image](https://cloud.githubusercontent.com/assets/5114190/22510030/710cc580-e8b6-11e6-80a8-be44f4a2d8d9.png)

**Comment by coderReview** [comment]
Can you try again? I will see if there was any crash in server. But when that happens it's automatically restarted. Just need a few minutes.

**Comment by nithyaasworld** [comment]
I accidentally deleted the app. So re-installed the app. Now I see no such problem.

I will again test #157 and update here if it occurs again.

**Comment by nithyaasworld** [comment]
No problem now.
