### ISSUE TITLE
Exported Report does not have Voice message associated with a newly created food item

### ISSUE THREAD

**Issue by nithyaasworld** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#169]
1. In iPad, create a new food item using Snap Photo option
2. After the food is added to consumption list, add a voice message
3. Now logout (to get synched)
4. In Admin Tool, generate a report for this user and observe

Actual:

Voice message associated with this newly created food item, is not available in the Report generated.

User: Jan23Test1
Food Data Added on: Feb 2nd 2017
Food Name with voice message: Eclairs Chocolate

![image](https://cloud.githubusercontent.com/assets/5114190/22617648/21f13fb2-eaf0-11e6-8d29-1e4b6c1a2411.png)

**Comment by coderReview** [comment]
@nithyaasworld Voice didn't get uploaded to server.

**Comment by coderReview** [comment]
Can you open the food details and see if the playback button is enabled?

**Comment by nithyaasworld** [comment]
It was enabled, when I was checking yesterday (Even after logging out and logging in back) and able to play too.

But now it is disabled. I will check the scenario again.

Thanks.

**Comment by nithyaasworld** [comment]
I am still able to reproduce by following the steps in the issue.

This happens to only the food added via Snap-a-photo option. No such problem with food added via Adhoc option.

**Comment by nithyaasworld** [comment]
It still happens.

One more update: If I add the voice message to an existing snap-a-photo food item which was created some 3 hours before, then there is no such problem.

**Comment by coderReview** [comment]
I can reproduce as well. Will have a fix soon.

**Comment by nithyaasworld** [comment]
Verified.

Report has voice message associated with food product added by snap-photo option.
