### ISSUE TITLE
Drinking Water - When added without Food Category and Origin

### ISSUE THREAD

**Issue by nithyaasworld** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#173]
@coderReview I am not sure if this is a valid scenario.

I just want to let you know that this happened, so logging this ticket.

When I uploaded a Food CSV file with Drinking water without specifying Origin or Category, I received the below error.

Please let me know what Origin should a Drinking water food product have

Uploaded File: 
[Food 2.csv.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/773111/Food.2.csv.zip)

![image](https://cloud.githubusercontent.com/assets/5114190/22914754/5c8324a6-f298-11e6-90dd-d3ba8798df0f.png)

**Comment by nithyaasworld** [comment]
Even If I have Origin as "NASA Foods" and upload, I still receive same error.

**Comment by coderReview** [comment]
Origin can be NASA Foods and category can be Drink

**Comment by coderReview** [comment]
You can't add food without origin and category. But I will try improving the error message

**Comment by nithyaasworld** [comment]
Ok. After adding Origin and category as stated above, I am able to add Fluid via the app.

**Comment by coderReview** [comment]
@nithyaasworld will improve the error message and make a new commit in 1h.

**Comment by nithyaasworld** [comment]
Thanks Paulo.

It shows correct error message.

![image](https://cloud.githubusercontent.com/assets/5114190/22941289/f0487c32-f30a-11e6-9516-16087f8f5136.png)
