### ISSUE TITLE
Not able to login to users when iPad is offline

### ISSUE THREAD

**Issue by nithyaasworld** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#175]
iPad 4 iOS 10.2

1. Switch off the wifi and try to login to any of the users

Actual:

I get error "User is already logged in another device"

Expected:

User should be allowed to login in offline mode.

**Comment by coderReview** [comment]
I think we have to leave like this. User can only login when online. After that if device goes offline it can continue to log food consumption records.
Why?
1- If device is offline a user lock cannot be created and more than one user can make changes to food records at once
2- If user was marked as removed (but still present in database), the offline device won't get that information and will mark the user as NOT removed and also add new records to a removed user

please confirm @szwart and @rsial2

**Comment by coderReview** [comment]
@nithyaasworld if confirmed I can improve the error message (when the server is offline) and disable login button when iPad has not internet connection

**Comment by szwart** [comment]
If we can only login when online, this will make it very difficult for us to train crews.  We've always been able to login when offline and the data are synced when the iPad is online again and we really like that feature.  
The risk of having multiple offline iPads adding food at the same time is very low, as is the risk of adding foods to a deleted user.

**Comment by coderReview** [comment]
@szwart. ok.

**Comment by coderReview** [comment]
@nithyaasworld can you test the following scenarios?

1- Disconnect iPad
2- Login with user
3- Add food consumption records
4- Delete user in Admin Tool 'User Data' tab.
5- Connect iPad

Expected result: Should be forced to logout

1- Disconnect iPad and Simulator
2- Login with same user on both
3- Add food consumption records on both
4- Connect iPad
5- Connect Simulator

Expected result: iPad should synchronize to server and user is simulator should be forced to logout

6- Logout with user in iPad
7- Login with user in simulator

Expected results: simulator should synchronize to server

**Comment by nithyaasworld** [comment]
I just added two foods when the device is in offline mode. 

Those two foods are stuck with the message "Uploading to server" as there is no network connection. 

Can we hide those loading indicator when the device is offline? is it possible?

**Comment by nithyaasworld** [comment]
2-->

> 1- Disconnect iPad
> 2- Login with user
> 3- Add food consumption records
> 4- Delete user in Admin Tool 'User Data' tab.
> 5- Connect iPad
> 
> Expected result: Should be forced to logout
> 

It is forced to logout, but added food record is saved to db. I am not sure if this is okay, because this food record was added after the user was marked for deletion.

**Comment by nithyaasworld** [comment]
3-->

1- Disconnect iPad
2- Login with user
3- Add food consumption records and **LOGOUT**
4- Delete user in Admin Tool 'User Data' tab.
5- Connect iPad and **LOGIN**

this time, user is removed from Delete tab and put back in User tab. Added Food records are also saved to db.

**Comment by nithyaasworld** [comment]
4-->

1- Disconnect iPad and Simulator
2- Login with same user on both
3- Add food consumption records on both
4- Connect iPad
5- Wait iPad to synchronize
6- Connect Simulator
7- Now user is forced to logout as expected
**8- Try to login again in simulator for the same user**

Actual: User is now logged in simulator as well as in iPad when both systems are online. Added food records in simulator are also preserved.

**Comment by nithyaasworld** [comment]
@coderReview 

I would suggest to fix no:1 ( https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/issues/175#issuecomment-279912977 ) above as it prevents the user from editing the added food in offline mode.

For no: 2, 3 and 4, If its easy for you to fix, lets fix. Otherwise I would suggest not to worry as  @szwart has stated that "The risk of having multiple offline iPads adding food at the same time is very low, as is the risk of adding foods to a deleted user."

**Comment by coderReview** [comment]
@nithyaasworld 

I will fix no 1, 3 and 4.

**Comment by coderReview** [comment]
@nithyaasworld fixed

**Comment by nithyaasworld** [comment]
For no:1, I am able to edit only the time and quantity. I am not able to open the added food record,so I am not able to add comment or voice message.

(I am still checking other scenarios. I will update once done)

**Comment by nithyaasworld** [comment]
No:3 and 4 are verified.

Only No:1 is pending.

**Comment by coderReview** [comment]
@nithyaasworld done.

**Comment by nithyaasworld** [comment]
No:1 is also verified.

Also the below scenario is verified:

1. Disconnect iPad and login to any user
2. In Admin Tool Remove some Food products
3. In iPad try to add the removed food item and observe

Outcome: Removed food item is added in red colour and the food inventroy list is updated.
