### ISSUE TITLE
App crashes on adding food via Scan bar code for the first time

### ISSUE THREAD

**Issue by nithyaasworld** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#181]
1. Launch the app and create a new user (not necessary though)
2. Scan a valid barcode and add a food 
3. Observe

Actual:

App crash

Expected:

No crash

**Comment by nithyaasworld** [comment]
Crash Log

[Archive.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/795715/Archive.zip)

**Comment by coderReview** [comment]
fixed

**Comment by nithyaasworld** [comment]
Verified. No more crash.
