### ISSUE TITLE
Keep getting Error about not being able to connect to food repository

### ISSUE THREAD

**Issue by szwart** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#183]
I'm connected to the internet (confirmed by going to other websites), but keep getting an error that my iPad can't sync to the central food repository.  Also, I'm getting an error indicating that user Charlton Heston can't be logged in because he is already logged in another device.

**Comment by coderReview** [comment]
Amazon AWS had some issues in the past days. I will check if server is running. If you get lock issues go to admin tool and click on Release Lock button

**Comment by coderReview** [comment]
@szwart
Please try again. I will check the logs to see what is going on

**Comment by szwart** [comment]
I'm still not able to sync.

**Comment by coderReview** [comment]
Can you close the app and open it again? I can't see the logs from your device. Can you access the admin tool from the iPad browser?

**Comment by szwart** [comment]
I've closed the app and opened several times but keep getting that error message about the sync.  Yes - I just accessed the admin tool from the iPad browser.

**Comment by coderReview** [comment]
@szwart. Can you close the app, not just using the home button but actually stoping the app and start again? For some strange reason the logs are not being sent to the server I've set up.

**Comment by szwart** [comment]
Yes, I closed the app (swiped up) and tried to log in several times. I even restarted the iPad. I think you are not seeing the logs because it is not syncing, no?

On Mar 2, 2017, at 5:42 PM, Paulo Vitor Magacho <notifications@github.com<mailto:notifications@github.com>> wrote:


@szwart<https://github.com/szwart>. Can you close the app, not just using the home button but actually stoping the app and start again? For some strange reason the logs are not being sent to the server I've set up.

**Comment by coderReview** [comment]
@szwart the logs are sent to a server. but this is not working for your device. It was working last week.

**Comment by rsial2** [comment]
Sara are you on a network that allows external connections?

**Comment by szwart** [comment]
Yes - it worked fine from my office last week. I just tried from my home computer and I'm able to log in now to some of the profiles (some say they are in use right now). I will try again tomorrow from my office.

On Mar 2, 2017, at 6:34 PM, Rashid Sial <notifications@github.com<mailto:notifications@github.com>> wrote:


Sara are you on a network that allows external connections?

**Comment by coderReview** [comment]
@szwart what I find strange is that the logs for the iPad device you were testing is not showing in the log server dashboard. But I could see the logs from your iPad mini you tested yesterday night.
Is there any food consumption record that you've added that is showing the Synchronizing to Server message?

**Comment by szwart** [comment]
My iPad mini had no problem connecting to the server, so I’m not surprised you saw the logs from last night.  When I logged the foods last night, I believe I did see the message Synchronizing to Server.

I just tried the iPad in my office and it is still giving me the error message about not being able to sync.  I logged in as a user and tried to add a food and now it’s stuck with an “Uploading to server” message over that food item.  I can add more foods, and now they all indicate “Uploading to server” with a little wheel spinning around.  Previously, if we weren’t connected to the server, we did not see this perpetual message.

Recently on ISS we had a similar situation where the crew got the message that they were unable to sync. It happened within days of another crewmember manually registering as a user and using the app and folks on the ground thought that might have caused the issue.  The user profiles were wiped and reloaded and the iPads were able to sync again for a few days but then they got the error message again.  Finally, the app was wiped and reloaded and that seems to have fixed the problem.  I wonder if that sync issue is the same thing I’m experiencing now?

**Comment by szwart** [comment]
FYI – I tried using my phone hotspot to connect and I’m still getting the error message.

**Comment by coderReview** [comment]
@szwart normally this is because some food record is not being able to synchronize to the server and is blocking the synchronization.

**Comment by szwart** [comment]
FYI- I just deleted the app from my iPad and reloaded it, and now my iPad is syncing again.

**Comment by coderReview** [comment]
@szwart the logs are showing in the log server.

**Comment by coderReview** [comment]
@szwart yes. But now that I have the logs I will track what was the issue. Did the problem begin after you delete a food consumption record?

**Comment by szwart** [comment]
Unfortunately I can’t pinpoint when the sync problem started.  We had the iPad in the lab for testing, so there were several users testing it.  I will try to pay attention to this today!

Thanks!

**Comment by coderReview** [comment]
@szwart I think when you connected using your phone hotspot the logs started to show.

**Comment by szwart** [comment]
Actually, I was still getting the sync error message when connecting via hotspot.  After I reloaded the app, I'm not having the sync error anymore (connected via nasa wifi).

**Comment by coderReview** [comment]
@szwart when you removed the app any record that was not synchronized to the server was lost.

**Comment by szwart** [comment]
Yes…and that is what happened on ISS too…but we saw no way around it b/c we couldn’t get it to sync.

**Comment by rsial2** [comment]
@szwart, thanks for working with us on this.

@coderReview and @nithyaasworld this is a high priority issue. Need to make sure it's fixed.

**Comment by szwart** [comment]
I have not had any sync issues today since I reloaded the app, and have tried it off and on all day. It appears this might be fixed?

**Comment by rsial2** [comment]
@coderReview what do you think?

**Comment by coderReview** [comment]
@szwart can you delete a food consumption record and see if you get errors?

**Comment by szwart** [comment]
I deleted a bunch of food consumption records (by swiping to delete).  No errors.

**Comment by coderReview** [comment]
Ok. Can you use select the food and click the delete button on the top left?

**Comment by szwart** [comment]
I deleted a bunch of foods by deleting as you describe above and everything seems to be working fine.  No errors.

**Comment by coderReview** [comment]
Ok. Thanks.

**Comment by rsial2** [comment]
Closing this ticket.
