### ISSUE TITLE
Nutrient info for supplements

### ISSUE THREAD

**Issue by szwart** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#185]
I noticed that for 3 of the supplements (Nature's Bounty, One A Day, and Centrum Silver), they do not show any Nutrient info in the Daily Intake Report.  A grey bar "Data will be incorporated into ground analysis" shows up instead.  I checked the admin tool, and those items have zeros for calories, sodium, and fluid...shouldn't they show up as zeros instead of the grey bar?

**Comment by coderReview** [comment]
@szwart normally when all values are zeros the grey bar is shown. Only one of the nutrient value is different from zero the nutrients information is shown.

**Comment by szwart** [comment]
It would be nice to have the nutrient info even if they are zeros instead of the grey bar.  If this is a major change/fix, then do not worry about it.  Thanks!

**Comment by coderReview** [comment]
It will show zeros for Intake from Voice and Intake From Image. Is this ok?

**Comment by szwart** [comment]
Hmm...no, we should keep those as the grey bar indicating data will be incorporated on the ground.

**Comment by coderReview** [comment]
@rsial2 no change will be made here. I think we can close this. Please confirm @szwart

**Comment by szwart** [comment]
That is OK with us...

On Mar 3, 2017, at 9:39 PM, Paulo Vitor Magacho <notifications@github.com<mailto:notifications@github.com>> wrote:


@rsial2<https://github.com/rsial2> no change will be made here. I think we can close this. Please confirm @szwart<https://github.com/szwart>
