### ISSUE TITLE
Confirmation of all necessary files for version 1.8 delivery

### ISSUE THREAD

**Issue by cflottorp** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#192]
To confirm the latest download contains all the files needed since I was going to completely wipe the server and re-load from the zipped file downloaded from GitHub, we also need to reload all of the following  :
 
1)      Configparser
2)      Orderreddict
3)      Python crontab
4)      Setuptools
5)      Uuid
6)      Uuid-ossp
7)   Node.js
8)   Jade
9)   python
 Are there any other dependencies? Does the latest download in GitHub contain prior releases from the original version 1.7?

**Comment by rsial2** [comment]
@coderReview please review.

**Comment by coderReview** [comment]
@cflottorp and @rsial2 these are still needed

**Comment by rsial2** [comment]
@cflottorp, closing this issue. If it needs to be reopened, please do so and add a comment.

**Comment by cflottorp** [comment]
ok, thanks.
