### ISSUE TITLE
Verify the current version of the Admin_Tool_Architecture & Deployment Guide

### ISSUE THREAD

**Issue by cflottorp** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#193]
The App Documentation on GitHub has the Admin Tool process and screen shots that look similar to the current application.  Is this current or still needing to be updated? With the automation of the user and the data files, the user data and food data tabs shouldn't be needed. If the "reports" are run automatically, then the 'Reports' tab shouldn't be needed.

**Comment by rsial2** [comment]
@coderReview please review.

**Comment by rsial2** [comment]
@cflottorp why would we remove those tabs? They were built to provide manual use - and removing them from the admin tool can only really be done by @szwart. 

So until we hear otherwise, we won't be removing those tabs.

**Comment by cflottorp** [comment]
We use the csv files as the means to configure the food and users for use with the server and to maintain configuration control.

**Comment by rsial2** [comment]
I know :) I'm just saying that we can't remove screens from the admin tool without the project owners request / approval.

Gonna close this issue since the documentation is all up to date - we made sure everything was accurate.
