### ISSUE TITLE
Update ISS FIT script for the automatic integration of software necessary for the server

### ISSUE THREAD

**Issue by cflottorp** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#194]
The ISS FIT script is used to build and integrate the ISS FIT application software into the server software necessary for version 1.8.  It will need to be updated to include the processing of the files for TO 2.0 and 3.0 (version 1.8) which will include the intermediary service and the automatic report generation.   The original concept was to back up the previous version of the pl_fit and then merge the previous version with the new version. However, that concept has changed and not  the clean up script will be used to remove duplicates and then completely reload the pl_fit software to ensure the integrity of the pl_fit database.  I have attempted to update the script to remove the backup process but please review to ensure all unnecessary steps have been commented out or removed.  Due to conflicts in the naming of one of the directories, one directory has been renamed.  Also one of the dependences has been incorporated into the script instead (nodejs).  The file will be e-mailed separately due to the file content.

**Comment by rsial2** [comment]
@coderReview please work on this.

**Comment by coderReview** [comment]
@cflottorp should I run the script in a new server? I have an old image where I've developed the previous 0100_fit script.

**Comment by coderReview** [comment]
@cflottorp To be more specific I need the image of the system where this script needs to be applied.
Also, there are new files being used, like **postgres_uuid-ossp_extn_squeeze-amd64.tar.gz**.

**Comment by cflottorp** [comment]
The old image would be for the original and can be used to update.  The ISS FIT server software hasn't been updated on the server since that image.  There has been updates made since that time, for example, a modification to a permissions error and updating the SQL certificates, renaming some of the folder names and the uuid file may be the "produces a resultant ossp-uuid binary" (?).

**Comment by coderReview** [comment]
Should the script run on top of the server with the 1.0 code?

**Comment by cflottorp** [comment]
Not quite sure I understand, but  you probably have the "enchilada" service  pack which I think should already have the ISS FIT version 1.7 already loaded with the round 10.

**Comment by coderReview** [comment]
@cflottorp 

I have the service pack without any ISS FIT app loaded. I have the script to apply it. I just want to ask if I can do the following:

1- Use the enchilada service pack
2- Apply round 10 script 
3- Apply round 12 script (v1.8)

On step 2, for instance I've already installed/configured a lot of things that the script on step 3 won't need to reinstalled/configured. Can I do that?

What about the database? In my opinion we should rename the current database, make a backup to file and create the new (tables) one.

**Comment by cflottorp** [comment]
The only items that I currently know that have been applied to the load are libsplc2, jade, python-egenix.  The other_files from Round 11 and 12 would not have been loaded yet.

**Comment by rsial2** [comment]
how's this coming along @coderReview?

**Comment by rsial2** [comment]
@cflottorp we are going to send you these files via email, and not post them in Basecamp.

**Comment by rsial2** [comment]
Closing this issue since the script was sent via email.
