### ISSUE TITLE
iPad Sync When DB Has Been Cleared

### ISSUE THREAD

**Issue by rsial2** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#61]
Implement functionality so that if a DB is cleared, the app will download any new data automatically. Right now it requires the app to be deleted and re-installed to get the new data.

**Comment by szwart** [comment]
Can you clarify this?  We were under the impression that if the DB changes at all, the app constantly syncs to it and thus new foods or deleted foods will be reflected.

**Comment by rsial2** [comment]
Sure, what this means is if a developer or someone who has access to the database clears the entire database of all data and then uploads the data again (but not through the admin tool) - if in the event that happens, that app won't accept the new data.

But this is an edge-case. If someone is using the admin tool, and does a bulk upload into the admin tool, or manually deletes foods in the admin tool, we're fine, and nothing changes, the app will always accept the data.

We only need this functionality in case someone who is technical removes all data from the database.

So to confirm, using the admin tool for bulk updates and manual updates works and there's no issues there :)

**Comment by szwart** [comment]
Would this change the functionality of the app at all?  Would this fix mean that every time we open the app, we will see the "Loading..." bar which takes up to 5 min?  We definitely don't want to have to wait that long each time we open the app on the ground.  We are leaning away from this fix as it seems pretty remote.

**Comment by rsial2** [comment]
Nope, nothing changes for the user. The loading bar is still going to occur every time you install the app (but only when you install the app).

This is just in case anyone ever accidentally deletes the entire database of foods. If that happens, it would require users to delete the app and re-install the app to get the data to re-load.

**Comment by szwart** [comment]
OK - we are fine pressing without completing this optional fix.
