### ISSUE TITLE
Daily Intake Report

### ISSUE THREAD

**Issue by szwart** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#69]
When a voice recording or picture is taken, the grey bar that reads "Nutrient Data Pending Ground Uplink" needs to be changed to "Data will be incorporated into ground analysis"

**Comment by rsial2** [comment]
@szwart, can we capitalize the first letter of each word? That'll match how we do thing elsewhere in the app.

**Comment by szwart** [comment]
Yes! That works.



On Jun 29, 2015, at 12:29 PM, Rashid Sial <notifications@github.com<mailto:notifications@github.com>> wrote:


@szwart<https://github.com/szwart>, can we capitalize the first letter of each word? That'll match how we do thing elsewhere in the app.

**Comment by rsial2** [comment]
Fixed.
