### ISSUE TITLE
Photos Not Loading

### ISSUE THREAD

**Issue by rsial2** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#73]
1. While on the Profile Edit page, if you select a photo and save it, nothing will occur. There is no prompt that the profile edit has been saved.

2. If you select Cancel while on the Profile Edit page, this error occurs:
![image](https://cloud.githubusercontent.com/assets/5807576/9067474/acab369a-3aab-11e5-9d39-69429208efe8.png)

3. If you go to the iPad app, no profile photos are loading.
![image](https://cloud.githubusercontent.com/assets/5807576/9067499/d7dcb136-3aab-11e5-98c1-786ec817b9ab.png)

**Comment by coderReview** [comment]
@rsial2 , will check it out.

**Comment by rsial2** [comment]
Thanks Paulo.

**Comment by coderReview** [comment]
Hi, I've found the issue. It's related to the change of database user. Since it's no longer a database superuser the function to import the image file is failing. Working to fix that. Thanks

**Comment by rsial2** [comment]
Thanks, please let me know once it's fixed.

**Comment by szwart** [comment]
Is this fix going to change the code for the app at all?  Or will it change the code for the Admin Tool?  Or both?

**Comment by coderReview** [comment]
Only the admin tool. I have to change how the uploaded image is saved to the Database.

**Comment by rsial2** [comment]
@coderReview, can you commit a fix today please?

**Comment by coderReview** [comment]
Yes

**Comment by rsial2** [comment]
Fixed
