### ISSUE TITLE
Apache Basic Communication

### ISSUE THREAD

**Issue by rsial2** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#80]
Please modify the app to use Apache basic authentication.  

We recognize that the use of Node.js is central to FIT.  

Perhaps you could proxy authentication for Node.js by implementing the mod_proxy module in Apache.

**Comment by coderReview** [comment]
@rsial2 , I need more details here. We are not using apache at all in this application. Postgres database is used to hold the encrypted password used for the FIT adminstration site. I could use [Passport](http://passportjs.org/) which is more robust authentication middleware for Node.js. But it will still rely on the postgres database to hold the encrypted password. We can consider also moving the Node.js server to use HTTPS.

**Comment by rsial2** [comment]
I'm on it!

**Comment by coderReview** [comment]
Just to let you know. Passport have support for HTTP basic or digest authentication methods.
