### ISSUE TITLE
PostgreSQL Connections

### ISSUE THREAD

**Issue by rsial2** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#81]
PostgreSQL should accept connections only from localhost, and not from clients (regardless of client type - SSC Clients, iPad, etc.)  

FIT appears to make connections from the iPad directly to PostgreSQL.  

We're asking that FIT only have its LS1 components connect database, and that the iPad app not directly connect to it.

**Comment by coderReview** [comment]
iPad cannot synchronize without PostgreSQL database. I don't understand the network architecture so I don't know what changes to make here.
