### ISSUE TITLE
Deployment Guide Updates

### ISSUE THREAD

**Issue by rsial2** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#82]
Related to #81 the FIT Deployment Guide appears to have 2 PostgreSQL-related settings that are misconfigured:

host    pl_fit  pl_fit_db       0.0.0.0/0       md5

listen_addresses = '*'                  # what IP address(es) to listen on;
 
These settings both tell PostgreSQL to accept connections from any host.

Please fix this. Please also make any required adjustments to the deployment guide, as required for items #80, #81, and this ticket too.

**Comment by rsial2** [comment]
FYI @coderReview, don't forget about this one.

**Comment by coderReview** [comment]
This is fixed already. Please close it. Thank you
