### ISSUE TITLE
Round 9 - Snap Photo / Show All Photos

### ISSUE THREAD

**Issue by rsial2** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#97]
1. Launch the app and login
2. click on camera icon and choose "Snap photo"
3. Click on "Show all photos"
4. Observe

Actual:

it redirects to summary page.

Expected:

it should show the Photo gallery page.

**Comment by coderReview** [comment]
This is the expected behavior. I will hide the button when you can'take click on them.

**Comment by coderReview** [comment]
@rsial2 maybe you should assign it to me.

**Comment by rsial2** [comment]
Sorry @coderReview, I meant to assign it to you. Please proceed with the fix.

@szwart, FYI.
