### ISSUE TITLE
Round 9 - Today's Nutrient Intake Progress

### ISSUE THREAD

**Issue by szwart** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#98]
When user swipes to the left, the pie chart is displayed for carbs/protein/fat.  We noticed that the pie chart appears black when opened on an iPad Air but looks like the normal colors when viewed on iPad 2 or 3.  Any ideas why this might be?

**Comment by rsial2** [comment]
Thanks Sara, we will find out why, and fix it.
