### ISSUE TITLE
Round 9 - Voice Recording

### ISSUE THREAD

**Issue by szwart** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#99]
1. Login
2. Press voice recording 
3. Record message 2 min (we let it time out)
4. Click done
5. On the Daily Intake Report, click on the voice recording and click play
6. Voice playback will start... 
4. Press Logout
Observation: playback continues to occur even after the user has logged out.  
Expected result:The playback should stop after logout.

**Comment by rsial2** [comment]
Thanks Sara, we'll fix this.
